[features]
seeds = false
[programs.localnet]
gluex = "Bez8zTCqWNFiWorJXE7jvz1XbSqbLLvSb6fRR2p85ZVB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/blake/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
