[features]
seeds = false
[programs.localnet]
glueu = "DzZByscRszKLgwFTVM6BMtbG8aBYXfWTbSU7sa9gj5a8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/blake/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
