name: glueu

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ./app/
        run: yarn install
      
      - name: Build
        working-directory: ./app/
        run: yarn build; yarn export
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: app/out
          publish_branch: gh-pages
